# Generated by Django 4.2.1 on 2023-09-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_lesson_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='viewer',
        ),
    ]
